### ISSUE TITLE
Not Cleaning Cron

### ISSUE THREAD

**Issue by urmila-patel** [Alekseon/CleanRunningJobs#2]
I have installed this module in to my magento 2 setup , but its not cleaning ,
Some questions 
1) When its called 
2) After which interval it will clean (3 minutes??)
3)For which status its checked (pending ??) (STATUS_RUNNING means pending ??)

**Comment by LiamKarlMitchell** [comment]
1. Plugin is called when Magento\Cron\Observer\ProcessCronQueueObserver is.
2. ```This extension fix this issue by marking "running" cronjobs as error if they are older than 3 hours.```
   See [line 61 of the plugin ](https://github.com/Alekseon/CleanRunningJobs/blob/master/Plugin/Magento/Cron/Observer/FixOldRunningSchedulesPlugin.php#L61)
3. STATUS_RUNNING See [line 65 of plugin](https://github.com/Alekseon/CleanRunningJobs/blob/master/Plugin/Magento/Cron/Observer/FixOldRunningSchedulesPlugin.php#L65)
